---
title: "2_baltimore_q"
author: "Spencer Rhea"
date: "10/10/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(dataRetrieval)
library(xts)
library(dygraphs)
```


```{r cars}
sites <- c('01589330',
           '01589320',
           '01589315',
           '01589316',
           '01589312')

site_meta <- readNWISsite(sites)
names(site_meta)

```



```{r, echo=FALSE}

bq <- readNWISdv(sites, 
                    parameterCd = '00060',
                    startDate = '2009-10-01',
                    endDate = '2019-10-01') %>%
  rename(q_cfs = X_00060_00003,
         q_cd = X_00060_00003_cd) 


```


```{r, echo=FALSE}

bq_area <- bq %>%
  inner_join(site_meta %>% select(site_no, drain_area_va)) %>%
  mutate(q_cms = q_cfs*0.0283168) %>%
  mutate(q_cmd = q_cms*24*60*60) %>%
  mutate(drain_area_m2 = drain_area_va*2.58999*1000*1000) %>%
  mutate(q_mmpd = (q_cmd/(drain_area_m2))*1000)

```



```{r, echo=FALSE}
bq1 <- bq_area %>%
  filter(site_no == sites[1])

bq1_baseflow <- EcoHydRology::BaseflowSeparation(bq1$q_mmpd,
                                                 passes=3)

xts(bq1_baseflow,
    order.by = bq1$Date) %>%
  dygraph(.)

```


```{r, echo=FALSE}
q_keeper <- list()

for(i in 1:length(sites)) {
  bq1 <- bq_area %>%
  filter(site_no == sites[i])
  
  bq1_baseflow <- EcoHydRology::BaseflowSeparation(bq1$q_mmpd,
                                                   passes = 3) %>%
    mutate(site_no = sites[i],
           Date = bq1$Date) %>%
    rename(q_base = bt,
           q_mmpd = qft)
  q_keeper[[i]] <- bq1_baseflow
}

q_baseflow <- map_dfr(q_keeper, 
                  bind_rows)


```


```{r, echo=FALSE}
baseflower <- function(df){

  bq_baseflow <- EcoHydRology::BaseflowSeparation(df$q_mmpd,
                                                   passes = 3) 

  return(bq_baseflow)
}


bq_area_nest <- bq_area %>%
  group_by(site_no) %>%
  nest() %>%
  mutate(base_data = map(data, baseflower)) %>%
  unnest(data, base_data)

```
